repos:
  # Basic hygiene
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending

  # Ruff: format + lint
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.5
    hooks:
      - id: ruff-format
      - id: ruff
        args: [--fix]
        additional_dependencies: []

  # mypy: types
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy
        args: [--ignore-missing-imports, --pretty, --show-error-codes]
        additional_dependencies: [types-PyYAML]

  # detect secrets (prevents secrets in repo)
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args: ["--baseline", ".secrets.baseline"]

  # Run pytest quickly
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: bash -c 'pytest -q'
        language: system
        types: [python]
        pass_filenames: false

ci:
  skip: [pytest]   # keep CI fast if you enable pre-commit.ci later
